### ISSUE TITLE
SWIFT_VERSION '9.0' is unsupported, supported versions are: 4.0, 4.2, 5.0

### ISSUE THREAD

**Issue by neffex97** [kphanipavan/modal_progress_hud_nsn#1]
when i want to run my project on ios i faced this error 
```
SWIFT_VERSION '9.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'modal_progress_hud_nsn' from project 'Pods')
```
according to new flutter version all package should have at least pod 9.
so what should i do mate?
i think you need to update your pacakge

**Comment by kphanipavan** [comment]
I haven't been working much on this lately.

There is an alternative which supports all the platforms and can be found here: 
https://pub.dev/packages/modal_progress_hud_alt

Can you confirm if this works in your app?
I will try releasing a fix soon...
Sry for the inconvenience...

**Comment by neffex97** [comment]
thanks

**Comment by kphanipavan** [comment]
Hello!!
I have released an update to the package with support for more platforms. If possible, do test the package and report on any anomalies.

I am closing this issue, feel free to comment and reopen if this error is encountered.
