### ISSUE TITLE
Background in iOS

### ISSUE THREAD

**Issue by Sumitdhiman-HHC** [kphanipavan/modal_progress_hud_nsn#14]
On iOS Simulator and other small devices the background does not show, it shows only CircularProgressIndicator without background shadow. Users get confused, I clicked or not, because sometime app UI is dark and progress bar also dark so only progress bar does not shows. Let me know if it's related to the settings which I'm missing otherwise check in the library and provide the updated version of the library including fixed that issue.

**Comment by sixtysticks** [comment]
+1 ... I'm having same issue with this

**Comment by Sumitdhiman-HHC** [comment]
> +1 ... I'm having same issue with this

I found the solution:
Make a custom progress bar which will be better, as we can customise it according to our requirement and use it same as ModalProgressHud

Here is the example:

**class ProgressHUD extends StatelessWidget {
  final bool isShowing;
  final Widget child;

  const ProgressHUD({super.key, required this.isShowing, required this.child});

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        child,
        if (isShowing)
          const Positioned(
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
            child: ModalBarrier(dismissible: false, color: Colors.white30),
          ),
        if (isShowing) const Center(child: CircularProgressIndicator())
      ],
    );
  }
}**
