### ISSUE TITLE
WARNING: The plugin modal_progress_hud_nsn requires Andoird SDK 32.

### ISSUE THREAD

**Issue by HugoMorales** [kphanipavan/modal_progress_hud_nsn#4]
Just a warning that apperars everytime I compile my app, but it lets me run anyway.

Warning: The plugin modal_progress_hud_nsn requires Android SDK version 32.
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to C:\Users\Gorom\Documents\Projects\Flutter\fgc_reporter\fgc_reporter\android\app\build.gradle:
android {
    compileSdkVersion 32
    ...
}

**Comment by kphanipavan** [comment]
As the warning said, the compiled SDK version is set to 32 manually so it doesn't have to be changed frequently...

You can suppress this by opening `C:\Users\Gorom\Documents\Projects\Flutter\fgc_reporter\fgc_reporter\android\app\build.gradle` on your computer and manually replace `flutter.compileSdkVersion` to `32`.

![Screenshot_20220608_094054](https://user-images.githubusercontent.com/60005847/172529862-b1e95a33-2134-421a-9341-58b87ac47fd3.png)

**Comment by kphanipavan** [comment]
Closing this issue.
Feel free to reopen this issue if  necessary.
